<<<<<<< HEAD
services:
  app:
    build: .docker
    stdin_open: true
    tty: true
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      CHOKIDAR_INTERVAL: 100
    ports:
     - "5173:5173"
    volumes:
      - .:/app
      # exclude
      - /app/.git/
    working_dir: /app
=======
services:
  app:
    build: .docker
    stdin_open: true
    tty: true
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      CHOKIDAR_INTERVAL: 100
    ports:
     - "5173:5173"
    volumes:
      - .:/app
      # exclude
      - /app/.git/
    working_dir: /app
>>>>>>> 04d07dc2b3c9addf43aaf02abd573d1187506868
    user: 1000:1000